import { mutation } from "./_generated/server";

const SEED_PRODUCTS = [
    {
        name: "Hot Toys Iron Man Mark LXXXV",
        description: "1/6th scale collectible figure from Avengers: Endgame. Die-cast construction with over 50 points of articulation and LED light-up features.",
        price: 18500,
        originalPrice: 22000,
        images: ["/products/iron-man.jpg"],
        category: "action-figures" as const,
        brand: "Hot Toys",
        series: "Marvel Avengers",
        condition: "mint-in-box" as const,
        stock: 5,
        sold: 142,
        rating: 4.9,
        ratingCount: 87,
        tags: ["marvel", "iron-man", "die-cast", "premium", "LED"],
        isFeatured: true,
        isFlashSale: false,
    },
    {
        name: "S.H.Figuarts Spider-Man No Way Home",
        description: "Highly articulated action figure with multiple interchangeable hands and web effects. Includes Tom Holland head sculpt.",
        price: 4200,
        originalPrice: 5500,
        images: ["/products/spider-man.jpg"],
        category: "action-figures" as const,
        brand: "SHFiguarts",
        series: "Marvel Spider-Man",
        condition: "new" as const,
        stock: 12,
        sold: 305,
        rating: 4.8,
        ratingCount: 213,
        tags: ["marvel", "spider-man", "shf", "bandai"],
        isFeatured: true,
        isFlashSale: true,
        flashSaleEnd: Date.now() + 7 * 24 * 60 * 60 * 1000,
    },
    {
        name: "MAFEX Batman Hush",
        description: "Premium 6-inch action figure based on the iconic Batman: Hush comic. Includes batarang, grapple gun, and fabric cape.",
        price: 5800,
        images: ["/products/batman.jpg"],
        category: "action-figures" as const,
        brand: "Mafex",
        series: "DC Comics",
        condition: "new" as const,
        stock: 8,
        sold: 198,
        rating: 4.7,
        ratingCount: 156,
        tags: ["dc", "batman", "mafex", "medicom"],
        isFeatured: true,
        isFlashSale: false,
    },
    {
        name: "Dragon Ball Z Goku Ultra Instinct Statue",
        description: "12-inch premium resin statue featuring Goku in Ultra Instinct form. Hand-painted with LED base effects.",
        price: 12800,
        originalPrice: 15000,
        images: ["/products/goku.jpg"],
        category: "statues" as const,
        brand: "Banpresto",
        series: "Dragon Ball Z",
        condition: "mint-in-box" as const,
        stock: 3,
        sold: 67,
        rating: 4.9,
        ratingCount: 45,
        tags: ["anime", "dragon-ball", "goku", "statue", "LED"],
        isFeatured: true,
        isFlashSale: true,
        flashSaleEnd: Date.now() + 5 * 24 * 60 * 60 * 1000,
    },
    {
        name: "LEGO Star Wars UCS Millennium Falcon",
        description: "Ultimate Collector Series set with 7,541 pieces. Includes Han Solo, Chewbacca, Princess Leia, and C-3PO minifigures.",
        price: 42000,
        images: ["/products/millennium-falcon.jpg"],
        category: "model-kits" as const,
        brand: "LEGO",
        series: "Star Wars",
        condition: "new" as const,
        stock: 2,
        sold: 23,
        rating: 5.0,
        ratingCount: 19,
        tags: ["lego", "star-wars", "ucs", "premium"],
        isFeatured: true,
        isFlashSale: false,
    },
    {
        name: "Gundam RG Wing Zero Custom EW",
        description: "Real Grade 1/144 scale model kit. Features advanced inner frame and beautiful angel wing effect parts.",
        price: 2200,
        originalPrice: 2800,
        images: ["/products/gundam-wing.jpg"],
        category: "model-kits" as const,
        brand: "Bandai",
        series: "Gundam Wing",
        condition: "new" as const,
        stock: 20,
        sold: 412,
        rating: 4.6,
        ratingCount: 287,
        tags: ["gundam", "bandai", "model-kit", "real-grade"],
        isFeatured: false,
        isFlashSale: true,
        flashSaleEnd: Date.now() + 3 * 24 * 60 * 60 * 1000,
    },
    {
        name: "Jada Toys Batmobile 1989 1:24",
        description: "Die-cast metal Batmobile from Tim Burton's 1989 Batman. Includes Batman figure. Opening cockpit and rubber tires.",
        price: 1800,
        images: ["/products/batmobile.jpg"],
        category: "diecast" as const,
        brand: "Jada Toys",
        series: "DC Comics",
        condition: "new" as const,
        stock: 15,
        sold: 156,
        rating: 4.5,
        ratingCount: 98,
        tags: ["dc", "batman", "diecast", "batmobile"],
        isFeatured: false,
        isFlashSale: false,
    },
    {
        name: "One Piece Monkey D. Luffy Gear 5 Figure",
        description: "Premium Ichiban Kuji prize figure of Luffy in Gear 5 Nika form. 10-inch tall with dynamic pose and cloud effects.",
        price: 3500,
        originalPrice: 4500,
        images: ["/products/luffy.jpg"],
        category: "action-figures" as const,
        brand: "Banpresto",
        series: "One Piece",
        condition: "new" as const,
        stock: 7,
        sold: 534,
        rating: 4.8,
        ratingCount: 321,
        tags: ["anime", "one-piece", "luffy", "gear-5"],
        isFeatured: true,
        isFlashSale: true,
        flashSaleEnd: Date.now() + 4 * 24 * 60 * 60 * 1000,
    },
    {
        name: "Naruto Shippuden Itachi Uchiha Statue",
        description: "Premium resin statue of Itachi Uchiha with Susanoo aura effect. 14-inch tall, limited edition with certificate.",
        price: 16500,
        images: ["/products/itachi.jpg"],
        category: "statues" as const,
        brand: "Tsume Art",
        series: "Naruto Shippuden",
        condition: "mint-in-box" as const,
        stock: 2,
        sold: 31,
        rating: 5.0,
        ratingCount: 28,
        tags: ["anime", "naruto", "itachi", "limited-edition"],
        isFeatured: true,
        isFlashSale: false,
    },
    {
        name: "McFarlane DC Multiverse The Flash",
        description: "7-inch action figure with 22 points of articulation. Includes Speed Force lightning effects and display base.",
        price: 1500,
        originalPrice: 1900,
        images: ["/products/flash.jpg"],
        category: "action-figures" as const,
        brand: "McFarlane",
        series: "DC Comics",
        condition: "new" as const,
        stock: 25,
        sold: 189,
        rating: 4.3,
        ratingCount: 142,
        tags: ["dc", "flash", "mcfarlane", "budget-friendly"],
        isFeatured: false,
        isFlashSale: true,
        flashSaleEnd: Date.now() + 6 * 24 * 60 * 60 * 1000,
    },
    {
        name: "Demon Slayer Tanjiro & Nezuko Set",
        description: "Twin-pack collectible figures of Tanjiro Kamado and Nezuko. Premium paint finish with water breathing effect parts.",
        price: 4800,
        images: ["/products/demon-slayer.jpg"],
        category: "action-figures" as const,
        brand: "Banpresto",
        series: "Demon Slayer",
        condition: "new" as const,
        stock: 10,
        sold: 267,
        rating: 4.7,
        ratingCount: 198,
        tags: ["anime", "demon-slayer", "tanjiro", "nezuko"],
        isFeatured: false,
        isFlashSale: false,
    },
    {
        name: "Transformers Masterpiece Optimus Prime",
        description: "Masterpiece MP-44 version 3.0. Die-cast parts, trailer included, fully transforms between robot and truck mode.",
        price: 28000,
        images: ["/products/optimus.jpg"],
        category: "action-figures" as const,
        brand: "Takara Tomy",
        series: "Transformers",
        condition: "mint-in-box" as const,
        stock: 3,
        sold: 45,
        rating: 4.9,
        ratingCount: 34,
        tags: ["transformers", "masterpiece", "optimus", "die-cast"],
        isFeatured: true,
        isFlashSale: false,
    },
];

export const seed = mutation({
    handler: async (ctx) => {
        // Delete all existing products to allow re-seeding with updated data
        const existing = await ctx.db.query("products").collect();
        for (const product of existing) {
            await ctx.db.delete(product._id);
        }

        for (const product of SEED_PRODUCTS) {
            await ctx.db.insert("products", {
                ...product,
                createdAt: Date.now(),
            });
        }

        return `Seeded ${SEED_PRODUCTS.length} products successfully!`;
    },
});
